public bool Active { get; set; }
public string AdminRole { get; set; }
public string ConfirmedPassword { get; set; }
public string Details { get; set; }
public string Email { get; set; }
public string FirstName { get; set; }
public string LastName { get; set; }
public string Password { get; set; }
public string PhoneNumber { get; set; }
public string PhotoPath { get; set; }
public long UserId { get; set; }
