public string AdvDetails { get; set; }
public float Cost { get; set; }
public string CostStatus { get; set; }
public DateTime ExpirationDate { get; set; }
public DateTime FromDate { get; set; }
public int HowManyDays { get; set; }
public long Id { get; set; }
public bool IsActive { get; set; }
public string PageLocation { get; set; }
public string PageName { get; set; }
public string PhotoPath { get; set; }
public long UserId { get; set; }
public long VisitorsClicks { get; set; }
