public string BlogCategoryName { get; set; }
public string Details { get; set; }
public string Heading { get; set; }
public long Id { get; set; }
public bool IsActive { get; set; }
public string PhotoPath { get; set; }
public DateTime PostedDate { get; set; }
public DateTime UpdatedDate { get; set; }
public long UserId { get; set; }
