public string Address { get; set; }
public string AdvDetails { get; set; }
public long CategoryId { get; set; }
public string ContactNo { get; set; }
public string Heading { get; set; }
public long Id { get; set; }
public bool IsActive { get; set; }
public bool IsSold { get; set; }
public string PhotoPath { get; set; }
public float Price { get; set; }
public long ReviewId { get; set; }
public long UserId { get; set; }
