public string AccountCreationDate { get; set; }
public string AccountUpdationDate { get; set; }
public long CompanyId { get; set; }
public string CompanyUniqueCode { get; set; }
public string ConfirmPassword { get; set; }
public string Email { get; set; }
public bool IsActiveAccount { get; set; }
public bool IsConfirmedEmail { get; set; }
public bool MadeCall { get; set; }
public string Password { get; set; }
public string UserName { get; set; }
