public string Address { get; set; }
public string City { get; set; }
public string ContactAt { get; set; }
public string ContactNumber { get; set; }
public long CustomerId { get; set; }
public string FullName { get; set; }
public long Id { get; set; }
public string OrderId { get; set; }
public string ZipCode { get; set; }
