public DateTime AccountCreationDate { get; set; }
public DateTime AccountUpdationDate { get; set; }
public string ConformPassword { get; set; }
public string CustomerUniqueCode { get; set; }
public string Email { get; set; }
public string EmailConfirmationCode { get; set; }
public long Id { get; set; }
public bool IsEmailConfirmed { get; set; }
public string Password { get; set; }
public string UserName { get; set; }
