public string ContactNo { get; set; }
public string Designation { get; set; }
public string DoctorName { get; set; }
public string FloorNo { get; set; }
public string HospitalName { get; set; }
public long Id { get; set; }
public bool IsActive { get; set; }
public string RoomNo { get; set; }
public string TntNumber { get; set; }
public long UserId { get; set; }
