public long CategoryId { get; set; }
public long CustomerId { get; set; }
public long Id { get; set; }
public string OrderedTime { get; set; }
public string OrderId { get; set; }
public long ProductId { get; set; }
public string ShippingStatus { get; set; }
public long SubCategoryId { get; set; }
public float TotalPrice { get; set; }
public int TotalQuantity { get; set; }
