public long CategoryId { get; set; }
public string Details { get; set; }
public float DiscountPrice { get; set; }
public long Id { get; set; }
public bool IsActive { get; set; }
public string Person { get; set; }
public string PhotoPath { get; set; }
public float Price { get; set; }
public string ProductName { get; set; }
public long Quantity { get; set; }
public long Sort { get; set; }
public long SubCategoryId { get; set; }
public long TotalArrivedQuantity { get; set; }
public string UpdatedAt { get; set; }
public long UpdatedBy { get; set; }
