public long CompanyId { get; set; }
public long CustomerId { get; set; }
public long Id { get; set; }
public string IsProblemSolved { get; set; }
public long ProductId { get; set; }
public long ReportCategoryId { get; set; }
public string ReportDetails { get; set; }
public string ReportedBy { get; set; }
public DateTime ReportingDate { get; set; }
