public DateTime AccountCreationDate { get; set; }
public DateTime AccountUpdationDate { get; set; }
public string Address { get; set; }
public string ConfirmPassword { get; set; }
public string Details { get; set; }
public string Email { get; set; }
public long Id { get; set; }
public bool IsActiveAccount { get; set; }
public bool IsConfirmedEmail { get; set; }
public string Password { get; set; }
public string PhotoPath { get; set; }
public string TransactionMethodStatus { get; set; }
public string UserName { get; set; }
public string UserUniqueCode { get; set; }
